name       : kxmlrpcclient
version    : 5.51.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kxmlrpcclient-5.51.0.tar.xz : 87b4974fc87f40bf5c51e81c22f372b855b0c0eecc32908f1817cc563abd4e3b
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
