name       : kxmlrpcclient
version    : 5.90.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/portingAids/kxmlrpcclient-5.90.0.tar.xz : 8cb23dc539fef71395947183c7c70a7a4c028086f2e8389b647a5b4ce2e30257
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - BSD-2-Clause
component  : programming.library
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
