name       : kxmlrpcclient
version    : 5.36.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.36/kxmlrpcclient-5.36.0.tar.xz : a181b54e093a257309d960c797159e7bcbeccee7aa5b59e4e708880045eca793
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
