name       : kxmlrpcclient
version    : 5.62.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.62/kxmlrpcclient-5.62.0.tar.xz : c284c3e5962d2ed6d0737e5814b85fa4d7926131b7799272cb56c464a12c4530
license    : BSD-2-Clause
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
