name       : kxmlrpcclient
version    : 5.54.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kxmlrpcclient-5.54.0.tar.xz : c69743cdafe74e7538baa7e857d9136b3a5a9122dcaecd3661be22ca0bf33aa5
license    : BSD-2-Clause
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
