name       : kxmlrpcclient
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/kxmlrpcclient-5.35.0.tar.xz : 5e003267c727828d88077a8493b7f7d545524f6fbc1bf85b7d07ce5f043cc514
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
