name       : kxmlrpcclient
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/kxmlrpcclient-5.32.0.tar.xz : 5875d0b5910696adce067b4076f8293deab070d58db6f06e2df036d756fc4ccd
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
