name       : kxmlrpcclient
version    : 5.48.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.48/kxmlrpcclient-5.48.0.tar.xz : 8074572d1244b1701e0149febe3e37445a3e37b1f2a3f5079acf4a7045cf1d68
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
