name       : kxmlrpcclient
version    : 5.74.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/portingAids/kxmlrpcclient-5.74.0.tar.xz : df71bc7082721c83fcccdc4bc221eb456bcff01cc50b29494ed3054e268363c9
homepage   : https://community.kde.org/Frameworks
license    : BSD-2-Clause
component  : programming.library
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
