name       : kxmlrpcclient
version    : 5.55.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kxmlrpcclient-5.55.0.tar.xz : 681402ad3527821459cfc0db5ac85f4248ca913f150737fafb522e27b6e5e394
license    : BSD-2-Clause
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
