name       : kxmlrpcclient
version    : 5.109.0
release    : 67
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/portingAids/kxmlrpcclient-5.109.0.tar.xz : b27584289fb89d9717862aaa780da072ffa272ebae0c46b72714cb9c4771d0b4
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - BSD-2-Clause
component  : programming.library
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
