name       : kxmlrpcclient
version    : 5.49.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.49/kxmlrpcclient-5.49.0.tar.xz : 06c0dc10623ecb1b844c47577a53229c7d5789f895902fda9ef21c7decb69250
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
