name       : kxmlrpcclient
version    : 5.56.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kxmlrpcclient-5.56.0.tar.xz : 14a300a68ac6ade06206ebfc296c5ae2aa55b6f95629f87e19fb055108bd56ae
license    : BSD-2-Clause
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
