name       : kxmlrpcclient
version    : 5.50.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/kxmlrpcclient-5.50.0.tar.xz : d90c38f0eb00f883b73e81f943e19c0920e23e45f8ddae410dfaaf89c0eab80f
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
