name       : kxmlrpcclient
version    : 5.52.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kxmlrpcclient-5.52.0.tar.xz : 5514c0749b2c601d1ab3241120bef0ad30e382a7994d71d0e0470fae266f46e9
license    : BSD-2-Clause
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
