name       : kxmlrpcclient
version    : 5.41.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.41/kxmlrpcclient-5.41.0.tar.xz : 27e66dc96c787069583dc44a80f29c27a3ac0e3482a8694664df28146637f678
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
