name       : kxmlrpcclient
version    : 5.38.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.38/kxmlrpcclient-5.38.0.tar.xz : 4a79382406f247bd9ace01859cb92948e74e48c7abb94b9e47066f0453812a3d
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
