name       : kxmlrpcclient
version    : 5.65.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kxmlrpcclient-5.65.0.tar.xz : 2b29df46f16c606488238c7936b8cfc198f06549e01ad4b52cae0cb66fa85282
homepage   : https://community.kde.org/Frameworks
license    : BSD-2-Clause
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
