name       : kxmlrpcclient
version    : 5.57.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.57/kxmlrpcclient-5.57.0.tar.xz : d47d5cc49f050dda3a26f7654226c0d124ca5ba5503a60e606307426bbe43b9d
license    : BSD-2-Clause
component  : programming
summary    : XML-RPC client
description: |
    This library contains simple XML-RPC Client support. It is a complete client and is quite easy to use. Only one interface is exposed to the world, kxmlrpcclient/client.h and of that interface, you only need to use 3 methods: setUrl, setUserAgent and call.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
